name: Build

on: [push, pull_request]

jobs:
  Build-modern-node:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: ['8', '10', '12', '13']
    runs-on: ${{ matrix.os }}
    name: build and test (${{ matrix.os }}|node-${{ matrix.node }})

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm ci
      - run: npm run lint
      - run: npm test

  Build-legacy-node-6:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: ['6']
    runs-on: ${{ matrix.os }}
    name: build and test (${{ matrix.os }}|node-${{ matrix.node }})

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install
      - run: npm test
